services:
  whos_online:
    class: BIT\BITWhosOnlineBundle\Services\WhosOnline\WhosOnlineService 
    arguments:
      config:
        single_session: %whos_online.single_session%
        db_options: %whos_online.db_options%
        logout_path: %whos_online.logout_path%
      session:  @session
      security_context:  @security.context
      whos_online_object_manager:  @whos_online.object_manager
      logger: @logger
    tags:
        - { name: monolog.logger, channel: whosonline }
        
  whos_online.object_manager:
    class: BIT\BITWhosOnlineBundle\Services\ObjectManager\MongoDBObjectManager
    arguments:
      entity_manager: @doctrine.odm.mongodb.document_manager